swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
definitions:
  models.AuctionItem:
    title: AuctionItem
    type: object
    properties:
      bid_multiple:
        type: integer
        format: int64
      buy_now:
        type: integer
        format: int64
      current_bid:
        type: integer
        format: int64
      description:
        type: string
      finish_date:
        type: string
        format: datetime
      id:
        type: integer
        format: int64
      id_auctioneer:
        type: integer
        format: int64
      id_choosen_bidder:
        type: integer
        format: int64
      picture:
        type: string
      publish_date:
        type: string
        format: datetime
      start_bid:
        type: integer
        format: int64
      stock_condition:
        type: string
